name: loanapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  # firebase_core: ^2.26.0
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  material_symbols_icons: ^4.2719.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
    - assets/images/coins.png


